#cat caddy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2
  namespace: cinjith
  annotations:
    kubernetes.io/change-cause: "image tag updating to caddynline-perl for nginx"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: c1
        image: caddy