apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-cb
  namespace: cinjith
  annotations:
    kubernetes.io/change-cause: "Revision two"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: c1
        image: nginx
      - name: c2
        image: redis